src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Previously, the db-up? function could potentially hang indefinitely, which is never what we want. This change gives the function one second to connect, returning false if it fails to do so in that time.

(maint) Add a one-second timeout to `db-up?`

---

.travis.yml
test/puppetlabs/jdbc_util/core_test.clj

Remove the modification of the test-db config performed in the fixture
that resets the test db, since it's confusing & error-prone to modify
the DB config with environment variable values in two different places,
and isn't necessary.
Change the name of the environment variables used to set the DB
configuration to `JDBCUTIL_DB*`, where `*` is one of `NAME`, `USER`, or
`PASS`. This is consistent with the convention our other projects have in
naming these environment variables.

(maint) There can be only one test DB config.

---

project.clj
src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Add the `connection-pool` function to the core namespace, which takes
a DB spec defined using the :subprotocol, :subname, :user, and :password
keys and turns it into a DB spec with just a :datasource key, whose
value is a pooled DataSource object.

(PE-9468) Add shared `connection-pool` function.

---

.travis.yml
project.clj
src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Switch from BoneCP to HikariCP to take advantage of the latter's built-in connection retrying. This commit leaves HikariCP's default 30 second timeout for failed connections.
*NB*: the test adds about 30 seconds to each test run, which kind of sucks. I'm not sure if there's a better way, but I'm more than open to suggestions.

(PE-9470) Add connection retrying via HikariCP

---

dev-resources/log4j.properties
project.clj
src/puppetlabs/jdbc_util/core.clj

This adds debug logging to the db-up? function, which is failing in acceptance tests.
In addition, it enables debug log output for the puppetlabs.jdbc-util.core namespace when the tests are running.

(maint) add debug logging for test failures

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Log at a useful level and with a more verbose message when this fails or times
out. Since this is in the service status check failures should be seen by the
user.

(PE-15268) Improve logging for db-up? failure

---

README.md
project.clj
src/puppetlabs/jdbc_util/pool.clj

In the first implementation the `init-fn` used by `pool/connection-pool-with-delayed-init` was passed a single database connection. Since java.jdbc closes connections on each operation unless using a transaction, this changes the API so that `init-fn` is passed a map containing the datasource. This map can be passed directly to java.jdbc calls.
I have also added some documentation.

Fix init function API

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Add the `convert-result-pgobjects` function, which converts all
PGobjects to whatever their getValue method returns.
Change `query` to use the above function.
Add a test that ensures that a UUID value retrieved from the database is
converted to a java.util.UUID by way of `convert-result-pgobjects`.

(PE-15534) Query converts PGObjects to their vals.

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Add has-extension, has-pglogical-extension, and wrap-ddl-for-pglogical.
These will be used by console-services projects to correctly execute
DDL when pglogical is installed.

(PE-14381) Add pglogical utility functions

---

src/puppetlabs/jdbc_util/pool.clj

Setting this in wrap-with-delayed-init was making it impossible to configure
independently. Since the datasource's regular connection timeout is already
the default, this also served no purpose. Remove it and add a utility function
for setting the timeout.

(maint) Make connectivity check timeout configurable

---

src/puppetlabs/jdbc_util/pglogical.clj

Changes exception behavior of update-pglogical-replication-set. If the
db user don't have rights to update pglogical, catches the exception and
returns false. Other exceptions are passed through.
This fixes db migration crashes in users of this function when pglogical
is installed but the database is read-only.

(maint) Catch perm error in replication set update

---

src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/pool_test.clj

Augment the `set-option` function to handle setting the connection
health check timeout, rather than requiring users to call a separate
function to add that to the config (unlike all the other configuration
options).

(maint) Improve UX of setting check timeout.

---

README.md
locales/messages.pot
project.clj
src/puppetlabs/jdbc_util/core.clj
src/puppetlabs/jdbc_util/migration.clj
src/puppetlabs/jdbc_util/pglogical.clj
src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/migration_test.clj
test/puppetlabs/jdbc_util/pglogical_test.clj
test/puppetlabs/jdbc_util/pool_test.clj

This PR changes the connection-pool-with-delayed-init function to
expect a migration-db-spec (a normal JDBC db-spec) with a migratus
:migration-dir assoc'd on. This allows us to share the
pg-logical, migration code across all the projects using jdbc-util and
allows us to keep the initilization datasource and migration datasource
as separate entities (because for most of the projects already using the
init-fn, the init-fn really *should* be run as the application user, not
the migration user).
This PR also adds support functionality for getting the status of pglogical replication.

(PE-14580) replication status support

---

test/puppetlabs/jdbc_util/pool_test.clj

This commit changes the pool-tests to not pass in a migration-db so that
the migrations step of the initilization won't be run since it isn't
necessary in testing and we have tests for migrations.

(maint) Stop running migrations in pool-tests

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

In the event that a sequence object has fallen behind the column it tracks, this function will reset it.
This decreases our reliance on pglogical's sequence replication, which was just added and may not be perfectly reliable.

(PE-17037) Add reconcile-sequence-for-column! function

---

dev-resources/test-migrations/20140114131703-base-schema.up.sql
locales/messages.pot
project.clj
src/puppetlabs/jdbc_util/migration.clj
src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/pool_test.clj

This commit blocks the startup of replicas while there are pending
migrations (i.e. replicas will wait for the migrations to be replicated
from the master).

(PE-16181) Block replica startups waiting for migrations

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Prior to this commit, `reconcile-sequence-for-column!` would cause an error when given an empty column.
Specifically, it would attempt to set the sequence to 0, which is an illegal value. As of this commit, it will instead set the sequence to 1, passing an additional parameter that signals that the next value emitted should be the current value (i.e., post-increment instead of pre-increment).

(PE-15626) Fix reconcile-sequence-for-column!

---

locales/messages.pot
src/puppetlabs/jdbc_util/core.clj
src/puppetlabs/jdbc_util/pglogical.clj
test/puppetlabs/jdbc_util/pglogical_test.clj

This commit adds a timeout to the pglogical status check (like db-up?
has for the database connection check). Before this commit the
replication status check wouldn't timeout but the service level
trapperkeeper-status check would, putting the whole service in an
unknown state.

(PE-14580) Add timeout to pglogical status check

---

src/puppetlabs/jdbc_util/migration.clj
test/puppetlabs/jdbc_util/migration_test.clj

Previously, the output of spec->migration-db-spec could:
1. contain nil values for the :user and/or :password keys
2. match the :password value with the :migration-user value (or various
other permutations)
Neither of these is desirable. In practical usage, passwords are not
always supplied, in which case the key should not be present in the
final map. Furthermore, it should be fine to use passwords for
migrations but not for normal use, or vice-versa.
This commit addresses both problems.
Signed-off-by: Justin Holguin <justin.h.holguin@gmail.com>

(maint) Refine/de-nilify migration spec

---

CHANGELOG.md
src/puppetlabs/jdbc_util/core.clj

It's unnecessary to assume that we can't wait for a lock on a table for
updating sequence objects. This is more likely to cause problems than
prevent them.

(maint) Remove NOWAIT in seq reconciliation lock

---

project.clj

This update removes warning about empty migrations due to a previously
broken regex in migratus.

(maint) Update migratus dependency to 0.8.30

---

src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/pool_test.clj

An earlier change inadvertently caused the `.setInitializationFailFast` method to be called *after* the connection was made, at which point it had no effect. This commit restores the correct behavior.

(maint) set FailFast to false *before* connecting

---

MAINTAINERS

This change adds a reference to the Google group the maintainers are associated with.

(doc) Add internal_list key to MAINTAINERS

---

src/puppetlabs/jdbc_util/pglogical.clj
test/puppetlabs/jdbc_util/pglogical_test.clj

This function was using `case` incorrectly, which would cause it to always(?) report `:inactive` for replication status. This commit fixes the behavior.

(PE-17970) Fix consolidate-provider-status

---

README.md
locales/messages.pot
src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/pool_test.clj

There have been issues with the connection pool being closed prior to
the initialization routines completing.  This results in some
transient failures in tests as well as actual application.
The lifetime funcitons allow the caller to block until the init
routines are complete.  An interface to query the state of the init
routine completion is added.  Finally an interface is provided to
attempt to cancel the init routine, if possible.
Many of the pool unit tests were failing to close the pool after the test was done. 
`with-open` was applied to help with that issue.

(PE-18114) add lifetime protocol to pool

---

.gitignore
dev-resources/Makefile.i18n
project.clj

This enables adding the clj-i18n POT update automation job to the pipeline.

(maint) Update to i18n 0.6.0

---

README.md
dev-resources/log4j.properties
project.clj
src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Add functions that check the existence of, create, and destroy both
databases and users. They all take a DB spec as their first argument.
The DB spec should connect to a database that's not the one being
created or destroyed, and the user it connects as must have the
appropriate permissions for the operation.
Since CREATE/DROP statements cannot be parametrized as we
typically do with our Postgres queries, these functions rely on some
new utilites to verify that their inputs are safe.
Add `pg-sql-escape`, which takes an arbitrary string and returns it in
postgres's dollar-quoted format, which makes it safe to naively
interpolate into raw SQL strings. However, this can only be used in
places where postgres expects strings; it cannot be used to escape
identifiers such as the names of …

(TK-4352) Functions to Check Existence of, Create, and Destroy DBs & Users

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Replace `pg-sql-escape` and `safe-pg-identifier` with `pg-escape-string`
and `pg-escape-identifier`, which wrap Postgres's built-in escaping
facilities.

(maint) Use Postgres's escaping utilities.

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

The `create-user!` function in `puppetlabs.jdbc-util.core` now takes an optional options map where the `:superuser?` option will cause the function to create the new user as a superuser if the value is exactly `true`.
In addition, Improve the docstrings of `{create,drop}-{user,db}!` and `{user/db}-exists?` functions to talk about the correct things and be consistent with each other in structure & vocabulary.

(maint) Add superuser? option to `create-user!`

---

src/puppetlabs/jdbc_util/core.clj
test/puppetlabs/jdbc_util/core_test.clj

Previously, `create-db!` would throw an error when creating a database
owned by a different user than the user in the DB spec (unless the user
in the DB spec was a superuser). This is because postgres forbids users
from setting a database's owner to a role that they are not a member of.
Change `create-db!` to handle this case by having it check to see if the
DB spec user does have the required role membership. If not, it
temporarily grants the DB spec user the owner's role, creates the
database, and then revokes the role.

(maint) Create databases for other users

---

CHANGELOG.md
project.clj

Update to version 1.0.0
Update HikariCP to 2.6.1
Update dependencies to match current clj-parent project:
Update kitchensink to 0.3.0
Update cheshire to 5.7.1

(maint) move to 1.0.0 release and update deps

---

src/puppetlabs/jdbc_util/pool.clj

If a replica mode pool is requested, and an unexpected exception
occurs while the migrations are being performed for that pool,
the exeception isn't caught, nor logged.  This causes the init
pool routine to terminate unexpectededly.
This change catches unhandled exceptions in replica mode and logs
them.

(maint) unhandled exceptions in replica mode prevents startup

---

src/puppetlabs/jdbc_util/core.clj
src/puppetlabs/jdbc_util/pool.clj

In the more recent versions of Hikari, the config setting
'initializationFailFast' was deprecated in favor of
'initializationFailTimeout'  This updates the uses of
the fail-fast option to use the method sanctioned in
Hikari to disable the feature, namely use a timeout of
-1.

(maint) remove deprecations for initialization-fail-fast

---

CHANGELOG.md
project.clj
test/puppetlabs/jdbc_util/middleware_test.clj

This updates to the latest postgres driver and updates hikariCP to the
latest version.
The interfaces for the postgres errors changed, and required a slight
refactor of the test to get the correct error code to be generated.

(maint) update postgres version and hikariCP

---

.travis.yml
project.clj
src/puppetlabs/jdbc_util/migration.clj
test/puppetlabs/jdbc_util/pool_test.clj

Update libraries so that tests pass on Java 9.
The update to migratus will cause it to add two new columns to the migration
table. This should be handled transparently.

(maint) Update for Java 9

---

src/puppetlabs/jdbc_util/pglogical.clj
test/puppetlabs/jdbc_util/pglogical_test.clj

As part of the migratus update, migratus now does migration of
its own schema_migrations table.  This involves two commands
used to upgrade the database.  For pglogical support, a
wrapper was created that made sure the commands sent were wrapped
in the proper pglogical commands.
The wrapper assumed a single command being sent to be wrapped.
This updates the wrapper to handle both single commands, and a
sequence of commands.  It separates the sequence of commands
with semicolons.

(PE-23367) update pglogical-ddl-wrapper to support multiples

---

.travis.yml
CHANGELOG.md
README.md
project.clj
src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/core_test.clj
test/puppetlabs/jdbc_util/pool_test.clj

Previously, if an exception occurred while the pool was being created
it was logged, and connections were handed out normally.  This alters
the pool initialization behavior to:
* retry if transient failures occur during initialization
* log failures if non-transient failures are detected
* throw exceptions on getConnection attempts if the database failed to initialize correctly
This also increments the minor version number to 1.2 to indicate an interface
behavioral change.
Many test updates were made to improve the reliability of the tests.

(main) Improve pool migration and initialization behavior

---

README.md
test/puppetlabs/jdbc_util/pool_test.clj

The user wasn't being used, and causes problems on jenkins.  This
removes the user and the reference from the README.

(maint) remove the migrator user from pool test

---

test/puppetlabs/jdbc_util/core_test.clj

A test was eliminated that attempts to create a superuser using a non
superuser account.  This is just testing the psql behavior and is
problematic from a ci standpoint.

(maint) remove superuser test

---

CHANGELOG.md
src/puppetlabs/jdbc_util/migration.clj

Update the migration routine to check the state of the thread
interruption (which can happen via a cancellation) to allow
the migrations to terminate early.
Fix an issue where uncompleted-migrations left a database connection
open.

(maint) modify migration routine to observe thread interruptions

---

CHANGELOG.md
project.clj
src/puppetlabs/jdbc_util/migration.clj

Migratus 1.0.8 contains a feature to allow thread interruptibility.
This updates the pool to leverage that behavior in migratus and
removes a lot of logic that was duplicated from there.

(maint) update to migratus 1.0.8 and change migration function

---

CHANGELOG.md
src/puppetlabs/jdbc_util/pool.clj

In some circumstances, a close-after-ready was used.  The migrations
took longer than the timeout, which triggers the future cancellation.
Unfortunately, not waiting for the future cancel to have an impact prior
to closing the pool causes migratus to fail to clean up the migration
correctly, leaving it in a half-applied state.  This change causes
the pool to wait for the cancellation to have an impact, but also
applies a timeout to prevent a permanent wait scenario.

(PE-24859) wait for safe migration exit prior to closing pool

---

.travis.yml
CHANGELOG.md
src/puppetlabs/jdbc_util/core.clj
src/puppetlabs/jdbc_util/migration.clj
test/puppetlabs/jdbc_util/core_test.clj
test/puppetlabs/jdbc_util/pool_test.clj

The "uncompleted-migrations" function has the side-effect of creating
the migration table if it doesn't exist.  In the case where we are
a replica system, this can cause issues with pglogical based replication.
This alters the uncompleted-migrations routine to first determine
if the database table exists, and if it does, determine what migrations
remain.  In the case that the table doesn't exist, it returns the
list of all the uncompleted migrations.
It adds tests for the table-exists? function, as well as a test
that (which fails prior to the fix) demonstrates that the migrations
table isn't present when waiting for migrations in a replica scenario.
In a separate commit, update the changelog in preparation for a new release.

(PE-27018) uncompleted-migrations should have no side-effects 

---

.gitignore
CHANGELOG.md
project.clj
src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/pool_test.clj

This commit changes the migration dir key in the migration-opts
to accept multiple paths.

(PE-32628) support external data migrations

---

project.clj

This updates the repo to use the clj-parent project to define the
versions of dependencies included.  The clj-parent project allows
central management of dependencies.

(maint) update repo to use puppetlabs/clj-parent

---

.travis.yml
CHANGELOG.md
project.clj
src/puppetlabs/jdbc_util/pool.clj
test/puppetlabs/jdbc_util/pool_test.clj

setHealthCheckRegistry can no longer be set after HikariDataSource has been instantiated in HikariCP 5.x. Adds setting in the HikariConfig beforehand.

(PE-35357) Change setHealthCheckRegistry instantiation/a test to accomodate HikariCP 5.x

---

.github/workflows/lein-test.yaml

Useful to have for manually launching.

(RE-15185) Add workflow_dispatch to lein test gh action

---

project.clj

This commit updates clj-parent to 5.6.15 to update pgjdbc to version 42.4.5. While the vulnerable version was not shipped, it triggered scan warnings in all the projects that included jdbc-util.
Also:
- remove the unneeded dependency on log4j/log4j
- remove the version pins on log4j-over-slf4j and org.slf4j/slf4j-api to take up the versions in clj-parent

(PE-37972) update clj-parent for pgjdbc v42.4.5

---

.github/workflows/lein-test.yaml

The fixture for pg96 is soon to be retired, so this commit updates the github workflow to use pg14.

(PE-37271) Swap postgres96 for pg14 in gh workflow
